name: Sandbox_Build
run-name: Sandbox build triggered by ${{ github.actor }} on development branch
on: 
  push:
    branches:
      - development
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "kenlai212"
          password: "Maxsteel1596"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kenlai212/mr-public-web:development